### ISSUE TITLE
j.ui: pop-up menues are displaced on the screen

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#714] opened 2014-06-30 11:58 UTC
When hitting the pup-up menu icon in upper left corner of j.ui, the menu shows up in the upper left corner of the screen, just below the main menuba, instead of in the expected location.

The pop-up menu displaing names of parameters, messanges and returns have the same problem.

This problem only seem to happen when running Max in 64bit.

**Comment by lossius** [comment] 2015-10-27 20:35
I still have this problem with Max 7.0.6 in 64-bit mode and JamomaMax pulled and compiled today.

**Comment by tap** [comment] 2015-11-20 22:22
The previous problem occurred only when the patcher was in edit mode -- it was working correctly in presentation mode which is why I thought it was fixed.

There are two ways to address this.  I chose the easier of them in this commit but I'm not sure if it is desirable.  Perhaps @lossius or @reno- have thoughts?

This solution places the menu "near" (in my testing it was below) the j.ui object.  This means that it is offset from where you clicked but it leaves the entire view visible instead of obstructed by the menu.  This seems nice/desirable, but it's also a bit weird.

I'll assign to @lossius for review.

**Comment by reno-** [comment] 2015-11-23 11:37
I can confirm that menu is now below the module. I tried with different sizes of modules and the behavior is consistent.
Even if it's not exactly the "classis" behavior of a menu, I appreciate the fix, tx !

**Comment by matcham** [comment] 2015-12-10 17:02
having the popup menu appearing under the j.ui is ... strange :-s
especially when you have biiiig view !! (you click in the top left corner, and the menu appears far bellow the view...)
I would really prefer it to behave like a classic umenu...

**Comment by theod** [comment] 2015-12-14 14:49
this sounds like we need to reopen the issue...
I'm agree with @matcham : 
even if it better than having it on the top left corner of the screen, it still looks like a buggy menu.
I reassign to you @tap.

**Comment by lossius** [comment] 2016-04-20 11:54
I don't like the current position of the menu, and I definitively don't like the upper left corner of screen idea. IMHO this works in a similar way to e.g. a contextual menu that pops up when right-clicking in most apps. The menu pops up in the location where your mouse actually is when clicking. You click because you want to interact with the menu, and the menu will be gone once you've clicked what you wanted to click within it, so I don't see that there's any problem at all with having the menu showing up and covering pats of the j.ui object.

**Comment by lossius** [comment] 2016-04-20 12:44
I tried substituting 

    selectedId = jpopupmenu_popup_nearbox(p, (t_object*)x, patcherview, x->menu_selection+1);

for

    selectedId = jpopupmenu_popup_abovebox(p, (t_object*)x, patcherview, 0, x->menu_selection+1);

but this caused a linking error when compiling for 32bit.

**Closed** 2016-04-20 18:15 UTC
Labels: externals, priority/immediate, type/bug
